sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t nicemayi/docker-react -f Dockerfile.dev .

scripts:
  - docker run nicemayi/docker-react npm run test -- --coverage